development:
  adapter: postgresql
  encoding: unicode
  database: essence_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: essence_test
  pool: 5
  username:
  password: